describe('Crear nuevo miembro', () => {
    it('Debe permitir crear un nuevo miembro', () => {
      cy.login('nedrocoli@gmail.com', '12345678910')
      cy.visit("http://localhost:2368/ghost/#/members")
      cy.wait(1000)
      cy.get('#ember41 > :nth-child(1)').click()
      cy.get('#member-name').type('tester3')
      cy.get('#member-email').type('tester3@gmail.com')
      cy.get('.gh-member-label-input').type('prueba 1')
      cy.get('#member-note').type('Prueba 1')
      cy.get('section.view-actions > button').click()
      cy.wait(1000)
      cy.get('.gh-member-details-attribution > p').should('contain',"Created")
    })

    it('No debe permitir crear un nuevo miembro con un correo ya usado anteriormente', () => {
      cy.login('nedrocoli@gmail.com', '12345678910')
      cy.visit("http://localhost:2368/ghost/#/members")
      cy.wait(1000)
      cy.get('#ember41 > :nth-child(1)').click()
      cy.get('#member-name').type('tester3')
      cy.get('#member-email').type('tester3@gmail.com')
      cy.get('.gh-member-label-input').type('prueba 1')
      cy.get('#member-note').type('Prueba 1')
      cy.get('section.view-actions > button').click()
      cy.wait(1000)
      cy.get('.response').should('contain',"Member already exists.")
    })

    it('ISSUE: No debe permitir crear un nuevo miembro con el campo vacio de nombre', () => {
      cy.login('nedrocoli@gmail.com', '12345678910')
      cy.visit("http://localhost:2368/ghost/#/members")
      cy.wait(1000)
      cy.get('#ember41 > :nth-child(1)').click()
      cy.get('#member-name').type(' ')
      cy.get('#member-email').type('tester4@gmail.com')
      cy.get('.gh-member-label-input').type('prueba 4')
      cy.get('#member-note').type('Prueba 1')
      cy.get('section.view-actions > button').click()
      cy.wait(1000)
      cy.get('.gh-member-details-attribution > p').should('contain',"Created")
    })

    it('ISSUE: No debe permitir crear un nuevo miembro con los campos vacios, label, note y nombre', () => {
      cy.login('nedrocoli@gmail.com', '12345678910')
      cy.visit("http://localhost:2368/ghost/#/members")
      cy.wait(1000)
      cy.get('#ember41 > :nth-child(1)').click()
      cy.get('#member-name').type(' ')
      cy.get('#member-email').type('tester5@gmail.com')
      cy.get('.gh-member-label-input').type(' ')
      cy.get('#member-note').type('  ')
      cy.get('section.view-actions > button').click()
      cy.wait(1000)
      cy.get('.gh-member-details-attribution > p').should('contain',"Created")
    })

  })
